### ISSUE TITLE
Expected revenue in the end of the month for a Single City

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/invoice-explorer#4]
Assuming all pending notes (minus the ones late?) are paid.

<img width="196" alt="Screen Shot 2019-07-10 at 11 14 14 PM" src="https://user-images.githubusercontent.com/11580564/61017184-a021b280-a368-11e9-8e13-195f6b4619f4.png">

Related sdec-brasil/old-dashboard#60

**Comment by dbeyda** [comment]
### Request:
GET `/v1/cities/<city-id>/expected-revenue?month=3&year=2019`

### Response:
```
{
    "nInvoicesPending": 2,
    "expectedIssIncome":24
}
```

**Comment by tloriato** [comment]
Objetivo: Fornecer ao municipio quanto ele deve esperar receber no final do mês corrente. Não faz sentido falar de receita esperada para meses que já foram passados, e nota fiscal de serviço não é emitida para meses futuro (consulte com o Henrique).

Observações: Você precisa saber quando uma nota fiscal "vence" (Henrique) e calcular a partir daí, a soma dos valores das notas que vencem antes do final do mês corrente.

**Comment by dbeyda** [comment]
Changed endpoint to return the following:
* **alreadyPaid**: `valIss` of invoices emitted in the current month, that were already paid.
* **expectedMonthIncome**: **alreadyPaid** + `valIss` of invoices emitted in the current month, that are pending.
```
{
    "alreadyPaid": 0,
    "expectedMonthIncome": 25
}
```
