### ISSUE TITLE
Invoice Count grouped by Status from a Single City

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/invoice-explorer#6]
Both total value as count.

<img width="247" alt="Screen Shot 2019-07-10 at 11 02 35 PM" src="https://user-images.githubusercontent.com/11580564/61016846-80d65580-a367-11e9-8b2b-59c10e87ade0.png">

Related to sdec-brasil/old-dashboard#60

**Comment by dbeyda** [comment]
@tloriato  reviewing this, I don't think we should distinguish between 'pending' and 'waiting payment'. Both will have to be paid anyways.
Also, if we distinguish, it would make sense to 'distinguish late' pending from 'late awaiting payment'.

Can I close this? :smile:
