### ISSUE TITLE
Amount of Invoices in a Single City

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/invoice-explorer#8]
Given the city (prefeitura) X, we would like to have a breakdown of those values:

It's the amount of invoices issued *in* that city, basically a `count from all invoices where competencia = x`.

<img width="412" alt="Screen Shot 2019-07-10 at 10 51 08 PM" src="https://user-images.githubusercontent.com/11580564/61016485-225ca780-a366-11e9-8627-3ee4d1959dae.png">

Related to sdec-brasil/old-dashboard#60

**Comment by dbeyda** [comment]
@tloriato can we close this?

**Comment by tloriato** [comment]
Sure, daveboy

**Comment by tloriato** [comment]
Sure, daveboy
